### ISSUE TITLE
Incompatible with deepstack/deepstack-ui

### ISSUE THREAD

**Issue by bestlibre** [robmarkcole/tensorflow-lite-rest-server#26] opened 2020-07-20 10:36 UTC
I have tried to use both ` tensorflow-lite-rest-server` and [deepstack-ui](https://github.com/robmarkcole/deepstack-ui) but the processing of the picture produced this error in the server : 
```
"POST /v1/vision/detection HTTP/1.1" 422 Unprocessable Entity
```
The same picture sent with curl produces a result.

**Comment by robmarkcole** [comment] 2020-07-22 07:59
You are using the flask or fastapi version of this repo?

**Comment by bestlibre** [comment] 2020-07-22 08:16
I'm using the fastapi  (I have followed the Readme to install it). I managed to have a working version of deepstack-ui by bypassing the deepstack object and calling directly the tensorflow api with requests.

**Comment by robmarkcole** [comment] 2020-07-22 08:21
I guess you are querying from another machine? When you run the server include `--host 0.0.0.0` as arg

**Comment by bestlibre** [comment] 2020-07-22 08:34
I have created a Dockerfile for the tensor flow server, it is running in docker (I'm going to contribute the Dockerfile ASAP). And I already have the `--host` option in my docker `CMD`.

I think that the problem reside in the deepstack python binding and the expected image format in tensorflow server.  I have modified deepstack-ui with something like : 
```
-def process_image(pil_image, dsobject):
+def process_image(pil_image, dsobject, url):
     image_bytes = utils.pil_image_to_byte_array(pil_image)
-    dsobject.detect(image_bytes)
-    predictions = dsobject.predictions
+    if dsobject:
+        dsobject.detect(image_bytes)
+        predictions = dsobject.predictions
+    else:
+        img_type = filetype.guess(image_bytes)
+        resp = requests.post(url, files={"file":('image', image_bytes, img_type.mime)})
+        predictions = resp.json().get('predictions', [])
     return predictions
```
 and it's working. If you are interseted, I can make a Pull Request in deepstack-ui with my modifications.

**Comment by robmarkcole** [comment] 2020-07-22 09:21
Thanks for identifying the fix. That actually would be a PR on https://github.com/robmarkcole/deepstack-python

**Comment by bestlibre** [comment] 2020-07-22 09:29
Should the fix (sending the `mimetype` with the image) go in deepstack-python or in this repo (use `filetype` to find the type if it's not present in the request) ?

**Comment by robmarkcole** [comment] 2020-07-22 09:33
This should be an issue on deepstack-python with a complementary PR including a test to show the issue and a fix in the code. Once you have created the issue there I will close this one. Thanks

**Comment by robmarkcole** [comment] 2020-07-22 19:19
I believe this issue arises due to use of `file: UploadFile = File(...)`, might not be necessary if instead using `file: bytes = File(…)`

**Comment by robmarkcole** [comment] 2020-07-23 06:42
OK there are definitely benefits to using `UploadFile` (e.g. handle larger files like video) but the following is valid and compatible with deepstack:

```python
## The FastAPI
# https://fastapi.tiangolo.com/tutorial/request-files/
from fastapi import FastAPI, File
from PIL import Image
import io

app = FastAPI()

@app.post("/pillow/")
async def upload_image(file: bytes = File(...)):
    pil_image = Image.open(io.BytesIO(file))
    return {"pil_image_width": pil_image.width}

## The requests file
import requests

API_URL = "http://localhost:8000/pillow"

image_bytes = open("people_car.jpg", "rb").read()
response = requests.post(API_URL, files={"file": image_bytes}).json()
print(response)
```

**Comment by bestlibre** [comment] 2020-07-23 10:27
I have tested your branch. It's work. I have also tested with `UploadFile` and the same variable renaming you have done and it's working. Perhaps you can add a test with `filetype` in the server (if I keep the existing test it doesn't work) ?

**Comment by robmarkcole** [comment] 2020-07-23 10:29
@bestlibre how about the fastapi docs (also with UploadFile), do they render?

**Comment by bestlibre** [comment] 2020-07-23 12:18
What are the fastapi docs ?

**Comment by robmarkcole** [comment] 2020-07-23 12:49
https://fastapi.tiangolo.com/#interactive-api-docs

**Comment by bestlibre** [comment] 2020-07-23 16:14
I get the same result (with your branch or with UploadFile) : the page load but when I try to expand a section I get a never ending spinner

**Comment by robmarkcole** [comment] 2020-07-23 16:27
Likewise, I am surprised that could be due to renaming the variable from `file` to `image` but maybe.. It is a shame as the docs are interactive and very useful

**Comment by robmarkcole** [comment] 2020-07-24 06:20
OK missing docs not caused by renaming variable, must be the use of `bytes`

**Closed** 2020-07-24 06:31 UTC
